"""db07

Revision ID: 35039c719800
Revises: de2333717fef
Create Date: 2023-04-16 10:32:37.409750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35039c719800'
down_revision = 'de2333717fef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAuth',
    sa.Column('Id', sa.NVARCHAR(length=450), nullable=False),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('ISAuthenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Token',
    sa.Column('Id', sa.NVARCHAR(length=450), nullable=True),
    sa.Column('UserId', sa.NVARCHAR(length=450), nullable=False),
    sa.Column('TokenValue', sa.String(), nullable=True),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['UserAuth.Id'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('UserPassword',
    sa.Column('UserId', sa.NVARCHAR(length=450), nullable=False),
    sa.Column('HashString', sa.String(), nullable=True),
    sa.Column('saltString', sa.String(), nullable=True),
    sa.Column('EncriptedValue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['UserAuth.Id'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPassword')
    op.drop_table('Token')
    op.drop_table('UserAuth')
    # ### end Alembic commands ###
