"""db04

Revision ID: d4b78d6ed8b8
Revises: 28da2d31c1cd
Create Date: 2023-04-15 22:51:29.554458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd4b78d6ed8b8'
down_revision = '28da2d31c1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.alter_column('Group', 'CreatorId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.create_foreign_key(None, 'Group', 'UserInfo', ['CreatorId'], ['Id'])
    op.alter_column('JoinRequest', 'CreatorId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.alter_column('JoinRequest', 'GroupId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.create_foreign_key(None, 'JoinRequest', 'Group', ['GroupId'], ['Id'])
    op.create_foreign_key(None, 'JoinRequest', 'UserInfo', ['CreatorId'], ['Id'])
    op.alter_column('JoinedMember', 'GroupId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.alter_column('JoinedMember', 'MemberId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.create_foreign_key(None, 'JoinedMember', 'Group', ['GroupId'], ['Id'])
    op.create_foreign_key(None, 'JoinedMember', 'UserInfo', ['MemberId'], ['Id'])
    op.alter_column('Message', 'SenderId',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    op.create_foreign_key(None, 'Message', 'UserInfo', ['SenderId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.alter_column('Message', 'SenderId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_constraint(None, 'JoinedMember', type_='foreignkey')
    op.drop_constraint(None, 'JoinedMember', type_='foreignkey')
    op.alter_column('JoinedMember', 'MemberId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('JoinedMember', 'GroupId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_constraint(None, 'JoinRequest', type_='foreignkey')
    op.drop_constraint(None, 'JoinRequest', type_='foreignkey')
    op.alter_column('JoinRequest', 'GroupId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('JoinRequest', 'CreatorId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_constraint(None, 'Group', type_='foreignkey')
    op.alter_column('Group', 'CreatorId',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B611E1DD900')
    )
    # ### end Alembic commands ###
