"""db09

Revision ID: e3b1d16b1ba6
Revises: 74c471b31fcc
Create Date: 2023-04-18 22:54:27.630182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e3b1d16b1ba6'
down_revision = '74c471b31fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserAuth', 'ISAuthenticated')
    op.add_column('UserAuth', sa.Column('IsAuthenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAuth', sa.Column('ISAuthenticated', mssql.BIT(), autoincrement=False, nullable=True))
    op.drop_column('UserAuth', 'IsAuthenticated')
    # ### end Alembic commands ###
