"""db10

Revision ID: f323894f9d21
Revises: e3b1d16b1ba6
Create Date: 2023-04-18 23:17:14.799137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f323894f9d21'
down_revision = 'e3b1d16b1ba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
