"""db02

Revision ID: 73540038f284
Revises: 11d21dc2fd80
Create Date: 2023-05-10 09:13:20.855989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73540038f284'
down_revision = '11d21dc2fd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPassword')
    op.add_column('UserAuth', sa.Column('HashedPassword', sa.String(), nullable=True))
    op.add_column('UserAuth', sa.Column('SaltString', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserAuth', 'SaltString')
    op.drop_column('UserAuth', 'HashedPassword')
    op.create_table('UserPassword',
    sa.Column('UserId', sa.NVARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('HashedPassword', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SaltString', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['UserAuth.Id'], name='FK__UserPassw__UserI__534D60F1'),
    sa.PrimaryKeyConstraint('UserId', name='PK__UserPass__1788CC4C0CBAEAFB')
    )
    # ### end Alembic commands ###
