"""db04

Revision ID: a79fd0414e74
Revises: cfcfcfaa51b9
Create Date: 2023-05-31 08:29:58.691616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a79fd0414e74'
down_revision = 'cfcfcfaa51b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LastestMessage',
    sa.Column('GroupId', sa.NVARCHAR(length=450), nullable=False),
    sa.Column('MemberId', sa.NVARCHAR(length=450), nullable=False),
    sa.Column('MessageId', sa.NVARCHAR(length=450), nullable=True),
    sa.Column('WatchedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['GroupId'], ['Group.Id'], ),
    sa.ForeignKeyConstraint(['MemberId'], ['UserInfo.Id'], ),
    sa.PrimaryKeyConstraint('GroupId', 'MemberId')
    )
    op.drop_table('sysdiagrams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61ADA5F319')
    )
    op.drop_table('LastestMessage')
    # ### end Alembic commands ###
