"""add status model

Revision ID: b077c39e0d4f
Revises: b31fc697299d
Create Date: 2023-09-13 16:10:43.814303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b077c39e0d4f'
down_revision = 'b31fc697299d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('JoinRequest', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('JoinedMember', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('LastestMessage', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('Message', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('Token', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('UserAuth', sa.Column('Status', sa.Integer(), nullable=True))
    op.add_column('UserInfo', sa.Column('Status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserInfo', 'Status')
    op.drop_column('UserAuth', 'Status')
    op.drop_column('Token', 'Status')
    op.drop_column('Message', 'Status')
    op.drop_column('LastestMessage', 'Status')
    op.drop_column('JoinedMember', 'Status')
    op.drop_column('JoinRequest', 'Status')
    op.drop_column('Group', 'Status')
    # ### end Alembic commands ###
