"""db03

Revision ID: cfcfcfaa51b9
Revises: 73540038f284
Create Date: 2023-05-29 11:33:17.725717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcfcfaa51b9'
down_revision = '73540038f284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserInfo', sa.Column('JoinedDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserInfo', 'JoinedDate')
    # ### end Alembic commands ###
