"""db02

Revision ID: e6479fad2e7d
Revises: 06db96c19a0f
Create Date: 2023-06-01 09:44:09.856046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6479fad2e7d'
down_revision = '06db96c19a0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Token', 'TokenValue',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.NVARCHAR(length=450),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Token', 'TokenValue',
               existing_type=sa.NVARCHAR(length=450),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
